const BAN_LINES = [
  "Don't let the door hit you on the way out.",
  "Skill issue.",
  "You played yourself.",
  "The council has deliberated. The council has decided.",
  "Error 403: User Forbidden.",
  "Some people just can't be helped.",
  "Deleted.",
  "Thanks for coming. Please never return.",
  "Your presence has been permanently uninstalled.",
  "You have been yeeted into the shadow realm.",
  "Bye bye bye. ✌️",
  "Not even close, baby.",
  "Genuinely impressive how fast that happened.",
  "You were warned. You chose violence. Respect.",
  "Touch grass. Oh wait, you can't — you're banned.",
  "The exit has been permanently locked behind you.",
  "We do not miss you already.",
  "The ban hammer has spoken.",
  "This is your villain origin story. In someone else's server.",
  "Speedrun any%: get banned before reading the rules.",
  "GG EZ no re.",
  "You will not be simulated again.",
  "L + ratio + banned.",
  "Your appeal has been pre-denied.",
  "Permanently out of stock.",
  "We gave you rope. You found a way to hang yourself with it.",
  "The audacity. Truly. The unmitigated audacity.",
  "History will not remember you fondly.",
  "You have been manually removed from the gene pool of this server.",
  "Somewhere, a rules channel is weeping.",
  "Account terminated. No refunds.",
  "You absolute unit of a mistake.",
  "This one's going in the hall of shame.",
  "Zero ping. Zero chance. Zero return.",
  "Even the bots are embarrassed for you.",
  "Your legacy is a ban log entry.",
  "Ejected. No parachute.",
  "Unsubscribed. Muted. Blocked. Banned.",
  "The vibe was off from the start. This is the natural conclusion.",
  "One less problem.",
  "Archived and forgotten.",
  "Congrats — you made the list nobody wants to be on.",
];

const KICK_LINES = [
  "Touch grass.",
  "Come back when you've evolved slightly.",
  "You've been escorted off the premises.",
  "Security, please show this person out.",
  "Yote.",
  "You've been voted off the island.",
  "Go outside. Seriously.",
  "Respawn and try again.",
  "See you never. Or later. Probably never.",
  "Skill issue. Come back with more skill.",
  "You'll think about this one in the shower tonight.",
  "We just saved you from yourself.",
  "The vibe check: failed.",
  "You have been temporarily uninstalled.",
  "Kicked. It do be like that sometimes.",
  "Thank you for your service. Don't come back.",
  "Take a walk. Think about your choices.",
  "Escorted out by the vibes police.",
  "You had us in the first half, not gonna lie.",
  "Bye. Hope the next server is more your speed.",
  "Sent back to the lobby.",
  "Unfortunately, your vibe does not match this server's energy.",
  "One ticket to the outside, issued.",
  "Time to reflect. Outside. Away from here.",
  "Please collect your things.",
  "Not banned. Just… unwelcome.",
  "We'll keep your spot warm. No we won't.",
  "On behalf of the server, goodbye.",
  "Removed with the energy of a disappointed parent.",
  "Catch you on the flip side. Or don't.",
  "Your services are no longer required.",
  "Voted least likely to stay.",
  "You've unlocked: the exit.",
  "The bouncer has spoken.",
  "Return ticket not included.",
  "Gently, but firmly, removed.",
  "This isn't a ban, it's an opportunity to grow.",
  "Your invitation to remain has been rescinded.",
  "We're not mad. Just disappointed. And kicking you.",
  "Goodbye. Drive safe. Don't come back.",
];

const WARN_LINES = [
  "Consider this your one free mistake.",
  "The file has been opened. Don't add to it.",
  "Noted. And not in a good way.",
  "One strike down. Choose the next move wisely.",
  "This is your sign to read the rules again.",
  "The logs don't lie, and neither does this warning.",
  "We see you. We always see you.",
  "A friendly reminder that consequences are real.",
  "This warning has been personally signed by the ban hammer.",
  "Clip saved. Warning issued.",
  "Your behavior has been flagged, reviewed, and found lacking.",
  "Consider yourself officially on thin ice.",
  "The mods have noticed. That's not the flex you think it is.",
  "Strike registered. Proceed accordingly.",
  "You're collecting warnings like they're achievements.",
  "Every ban starts exactly like this.",
  "The council has taken note of your activities.",
  "Don't make us make this a ban.",
  "This goes on your permanent record.",
  "Logged, stamped, filed, and witnessed.",
  "You're one step closer to a permanent vacation.",
  "This is your yellow card. Red is next.",
  "Warned. The clock is ticking.",
  "This isn't a threat. It's a preview.",
  "Keep it up and see what happens. Actually, don't.",
];

const FORMAL_WARN_LINES = [
  "This is an official automated warning. Further violations will result in escalating consequences.",
  "Your behaviour has been flagged by the moderation system. Please review the server rules immediately.",
  "This warning has been recorded against your account. Continued infractions will lead to a mute or ban.",
  "You have reached the formal warning threshold. This is your final notice before automated action is taken.",
  "The moderation system has issued this warning in response to repeated rule violations. Please act accordingly.",
  "This is a system-generated formal warning. Your activity is being monitored and further violations will not be tolerated.",
  "Your account has accumulated enough violations to trigger a formal warning. We expect immediate improvement in conduct.",
  "This warning is a matter of record. Should you continue to violate the rules, further action will follow automatically.",
  "The automated moderation system has flagged your account. Please take this warning seriously.",
  "This formal notice is issued in accordance with server policy. Your next violation may result in a timeout.",
];

function pick(arr: string[]): string {
  return arr[Math.floor(Math.random() * arr.length)]!;
}

export function randomBanLine():  string { return pick(BAN_LINES);  }
export function randomKickLine(): string { return pick(KICK_LINES); }
export function randomWarnLine(): string { return pick(WARN_LINES); }

export function randomAutomodWarnLine(): string {
  return Math.random() < 0.5 ? pick(WARN_LINES) : pick(FORMAL_WARN_LINES);
}
